### ISSUE TITLE
excessive error messaging when parsing incorrect inputs

### ISSUE THREAD

**Issue by jsevo** [jsevo/taxumap#6]
There is some overengineeering going on wrt to the type checking of inputs. 

```python
from taxumap import Taxumap
import numpy
X = numpy.random.standard_normal(shape=(500,5))
tumap = Taxumap(rel_abundances  = X)
```

This passes the data as numpy array, which we currently do not accept. It raises repeated Errors and logs them, ending on an empty NameError. Let's aim to make that simple type checking a little less overly complicated.

```python
tumap = Taxumap(rel_abundances = X)
_name_value_error:ERROR
Please provide the constructor with one of the following: a filepath to your rel_abundances file via parameter `fpx`, or with an initialized variable for your rel_abundances dataframe via the parameter `rel_abundances`
Traceback (most recent call last):
  File "/Users/schluj05/workspace/phylo-umap/taxumap/taxumap/taxumap.py", line 112, in __init__
    raise NameError
NameError
_name_value_error:ERROR
Please provide the constructor with one of the following: a filepath to your rel_abundances file via parameter `fpx`, or with an initialized variable for your rel_abundances dataframe via the parameter `rel_abundances`
Traceback (most recent call last):
  File "/Users/schluj05/workspace/phylo-umap/taxumap/taxumap/taxumap.py", line 112, in __init__
    raise NameError
NameError
_name_value_error:ERROR
Please provide the constructor with one of the following: a filepath to your rel_abundances file via parameter `fpx`, or with an initialized variable for your rel_abundances dataframe via the parameter `rel_abundances`
Traceback (most recent call last):
  File "/Users/schluj05/workspace/phylo-umap/taxumap/taxumap/taxumap.py", line 112, in __init__
    raise NameError
NameError
_name_value_error:ERROR
Please provide the constructor with one of the following: a filepath to your rel_abundances file via parameter `fpx`, or with an initialized variable for your rel_abundances dataframe via the parameter `rel_abundances`
Traceback (most recent call last):
  File "/Users/schluj05/workspace/phylo-umap/taxumap/taxumap/taxumap.py", line 112, in __init__
    raise NameError
NameError
_name_value_error:ERROR
Please provide the constructor with one of the following: a filepath to your rel_abundances file via parameter `fpx`, or with an initialized variable for your rel_abundances dataframe via the parameter `rel_abundances`
Traceback (most recent call last):
  File "/Users/schluj05/workspace/phylo-umap/taxumap/taxumap/taxumap.py", line 112, in __init__
    raise NameError
NameError
_name_value_error:ERROR
Please provide the constructor with one of the following: a filepath to your rel_abundances file via parameter `fpx`, or with an initialized variable for your rel_abundances dataframe via the parameter `rel_abundances`
Traceback (most recent call last):
  File "/Users/schluj05/workspace/phylo-umap/taxumap/taxumap/taxumap.py", line 112, in __init__
    raise NameError
NameError
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-305-d8e2ccc3394d> in <module>
----> 1 tumap = Taxumap(random_state=1, rel_abundances = rX)

~/workspace/phylo-umap/taxumap/taxumap/taxumap.py in __init__(self, agg_levels, weights, rel_abundances, taxonomy, fpt, fpx, name, random_state)
    110             else:
    111                 #TODO currently only file paths or pd.DataFrame accepted. Passing a numpy array raises a NameError without explanation. Adding explanation now, but should be possible to pass a np.array
--> 112                 raise NameError
    113         except (ValueError, NameError) as e:
    114             _name_value_error(e, "fpx", "rel_abundances")

NameError: 


```

**Comment by jsevo** [comment]
This gets a bit worse when turning the data into a `pd.DataFrame`. 

```python
INFO:taxumap:Recognized `rel_abundances` parameter as Pandas DataFrame
__init__:ERROR
Your rel_abundances df needs to contain 'index_column' containing sample identifiers of each row containing relative OTU/ASV abundances
Traceback (most recent call last):
  File "/Users/schluj05/workspace/phylo-umap/taxumap/taxumap/taxumap.py", line 82, in __init__
    self.rel_abundances.set_index("index_column")
  File "/Users/schluj05/.ve/phylo-umap/lib/python3.8/site-packages/pandas/core/frame.py", line 4303, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['index_column'] are in the columns"
__init__:ERROR
Your rel_abundances df needs to contain 'index_column' containing sample identifiers of each row containing relative OTU/ASV abundances
Traceback (most recent call last):
  File "/Users/schluj05/workspace/phylo-umap/taxumap/taxumap/taxumap.py", line 82, in __init__
    self.rel_abundances.set_index("index_column")
  File "/Users/schluj05/.ve/phylo-umap/lib/python3.8/site-packages/pandas/core/frame.py", line 4303, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['index_column'] are in the columns"
__init__:ERROR
Your rel_abundances df needs to contain 'index_column' containing sample identifiers of each row containing relative OTU/ASV abundances
Traceback (most recent call last):
  File "/Users/schluj05/workspace/phylo-umap/taxumap/taxumap/taxumap.py", line 82, in __init__
    self.rel_abundances.set_index("index_column")
  File "/Users/schluj05/.ve/phylo-umap/lib/python3.8/site-packages/pandas/core/frame.py", line 4303, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['index_column'] are in the columns"
__init__:ERROR
Your rel_abundances df needs to contain 'index_column' containing sample identifiers of each row containing relative OTU/ASV abundances
Traceback (most recent call last):
  File "/Users/schluj05/workspace/phylo-umap/taxumap/taxumap/taxumap.py", line 82, in __init__
    self.rel_abundances.set_index("index_column")
  File "/Users/schluj05/.ve/phylo-umap/lib/python3.8/site-packages/pandas/core/frame.py", line 4303, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['index_column'] are in the columns"
__init__:ERROR
Your rel_abundances df needs to contain 'index_column' containing sample identifiers of each row containing relative OTU/ASV abundances
Traceback (most recent call last):
  File "/Users/schluj05/workspace/phylo-umap/taxumap/taxumap/taxumap.py", line 82, in __init__
    self.rel_abundances.set_index("index_column")
  File "/Users/schluj05/.ve/phylo-umap/lib/python3.8/site-packages/pandas/core/frame.py", line 4303, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['index_column'] are in the columns"
__init__:ERROR
Your rel_abundances df needs to contain 'index_column' containing sample identifiers of each row containing relative OTU/ASV abundances
Traceback (most recent call last):
  File "/Users/schluj05/workspace/phylo-umap/taxumap/taxumap/taxumap.py", line 82, in __init__
    self.rel_abundances.set_index("index_column")
  File "/Users/schluj05/.ve/phylo-umap/lib/python3.8/site-packages/pandas/core/frame.py", line 4303, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['index_column'] are in the columns"
ERROR:taxumap:Your rel_abundances df needs to contain 'index_column' containing sample identifiers of each row containing relative OTU/ASV abundances
Traceback (most recent call last):
  File "/Users/schluj05/workspace/phylo-umap/taxumap/taxumap/taxumap.py", line 82, in __init__
    self.rel_abundances.set_index("index_column")
  File "/Users/schluj05/.ve/phylo-umap/lib/python3.8/site-packages/pandas/core/frame.py", line 4303, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['index_column'] are in the columns"
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "/Users/schluj05/workspace/phylo-umap/taxumap/taxumap/taxumap.py", line 82, in __init__
    self.rel_abundances.set_index("index_column")
  File "/Users/schluj05/.ve/phylo-umap/lib/python3.8/site-packages/pandas/core/frame.py", line 4303, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['index_column'] are in the columns"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/schluj05/.ve/phylo-umap/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-320-d8e2ccc3394d>", line 1, in <module>
    tumap = Taxumap(random_state=1, rel_abundances = rX)
  File "/Users/schluj05/workspace/phylo-umap/taxumap/taxumap/taxumap.py", line 90, in __init__
    sys.exit(2)
SystemExit: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/schluj05/.ve/phylo-umap/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1148, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/Users/schluj05/.ve/phylo-umap/lib/python3.8/site-packages/IPython/core/ultratb.py", line 316, in wrapped
    return f(*args, **kwargs)
  File "/Users/schluj05/.ve/phylo-umap/lib/python3.8/site-packages/IPython/core/ultratb.py", line 350, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/Users/schluj05/.pyenv/versions/3.8.0/lib/python3.8/inspect.py", line 1503, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
AttributeError: 'tuple' object has no attribute 'tb_frame'
An exception has occurred, use %tb to see the full traceback.

---------------------------------------------------------------------------

During handling of the above exception, another exception occurred:

SystemExit: 2

/Users/schluj05/.ve/phylo-umap/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3339: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


```

**Comment by jsevo** [comment]
This also happens when Taxumap was instatiated successfully:
For example:

```python
from taxumap import Taxumap
import pandas as pd
import numpy as np

rX = pd.DataFrame(np.random.standard_normal((500, 15))).applymap(np.abs).apply(lambda r: r/r.sum(), axis=1)
rX.rename(columns={0:'index_column'}, inplace=True)

tax = pd.DataFrame([np.ones(14), np.arange(14)],index = ["Phylum", "Family"], columns=np.arange(14)+1, ).T
tax.iloc[10::, 0] = 2

tax = tax.astype(str)

tumap = Taxumap(rel_abundances=rX, taxonomy=tax)




```

```python
In [733]: tumap.transform_self()
transform_self:WARNING
Please set neigh parameter to approx. the size of individals in the dataset. See documentation.

transform_self:WARNING
Please set neigh parameter to approx. the size of individals in the dataset. See documentation.

transform_self:WARNING
Please set neigh parameter to approx. the size of individals in the dataset. See documentation.

transform_self:WARNING
Please set neigh parameter to approx. the size of individals in the dataset. See documentation.

transform_self:WARNING
Please set neigh parameter to approx. the size of individals in the dataset. See documentation.

transform_self:WARNING
Please set neigh parameter to approx. the size of individals in the dataset. See documentation.

WARNING:taxumap:Please set neigh parameter to approx. the size of individals in the dataset. See documentation.
INFO:taxumap:Setting min_dist to 0.05/sum(weights)
INFO:taxumap:Setting epochs to 1000
INFO:taxumap:aggregating on Phylum
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/.ve/phylo-umap/lib/python3.8/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2645             try:
-> 2646                 return self._engine.get_loc(key)
   2647             except KeyError:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index_class_helper.pxi in pandas._libs.index.Int64Engine._check_type()

KeyError: 'index_column'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-744-9ec2ce00224f> in <module>
----> 1 tumap.transform_self()

~/workspace/phylo-umap/taxumap/taxumap/taxumap.py in transform_self(self, scale, debug, save, outdir, **kwargs)
    356 
    357         # Shouldn't need `try...except` because any Taxumap object should have proper attributes
--> 358         Xagg = tax_agg(
    359             self.rel_abundances,
    360             self.taxonomy,

~/workspace/phylo-umap/taxumap/taxumap/taxumap.py in tax_agg(rel_abundances, taxonomy, agg_levels, distance_metric, weights)
    502     for agg_level, weight in zip(agg_levels, weights):
    503         logger.info("aggregating on %s" % agg_level)
--> 504         Xagg = tools.aggregate_at_taxlevel(_X, taxonomy, agg_level)
    505         Xagg = ssd.cdist(Xagg, Xagg, distance_metric)
    506         Xagg = pd.DataFrame(Xagg, index=_X.index, columns=_X.index)

~/workspace/phylo-umap/taxumap/taxumap/tools.py in aggregate_at_taxlevel(X, tax, level)
     15     """Helper function. For a given taxonomic level, aggregate relative abundances by summing all members of corresponding taxon."""
     16     _X_agg = X.copy()
---> 17     _X_agg.columns = [tax.loc[x][level] for x in _X_agg.columns]
     18     _X_agg = _X_agg.groupby(_X_agg.columns, axis=1).sum()
     19     try:

~/workspace/phylo-umap/taxumap/taxumap/tools.py in <listcomp>(.0)
     15     """Helper function. For a given taxonomic level, aggregate relative abundances by summing all members of corresponding taxon."""
     16     _X_agg = X.copy()
---> 17     _X_agg.columns = [tax.loc[x][level] for x in _X_agg.columns]
     18     _X_agg = _X_agg.groupby(_X_agg.columns, axis=1).sum()
     19     try:

~/.ve/phylo-umap/lib/python3.8/site-packages/pandas/core/indexing.py in __getitem__(self, key)
   1766 
   1767             maybe_callable = com.apply_if_callable(key, self.obj)
-> 1768             return self._getitem_axis(maybe_callable, axis=axis)
   1769 
   1770     def _is_scalar_access(self, key: Tuple):

~/.ve/phylo-umap/lib/python3.8/site-packages/pandas/core/indexing.py in _getitem_axis(self, key, axis)
   1963         # fall thru to straight lookup
   1964         self._validate_key(key, axis)
-> 1965         return self._get_label(key, axis=axis)
   1966 
   1967 

~/.ve/phylo-umap/lib/python3.8/site-packages/pandas/core/indexing.py in _get_label(self, label, axis)
    623             raise IndexingError("no slices here, handle elsewhere")
    624 
--> 625         return self.obj._xs(label, axis=axis)
    626 
    627     def _get_loc(self, key: int, axis: int):

~/.ve/phylo-umap/lib/python3.8/site-packages/pandas/core/generic.py in xs(self, key, axis, level, drop_level)
   3535             loc, new_index = self.index.get_loc_level(key, drop_level=drop_level)
   3536         else:
-> 3537             loc = self.index.get_loc(key)
   3538 
   3539             if isinstance(loc, np.ndarray):

~/.ve/phylo-umap/lib/python3.8/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2646                 return self._engine.get_loc(key)
   2647             except KeyError:
-> 2648                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   2649         indexer = self.get_indexer([key], method=method, tolerance=tolerance)
   2650         if indexer.ndim > 1 or indexer.size > 1:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index_class_helper.pxi in pandas._libs.index.Int64Engine._check_type()

KeyError: 'index_column'


```

**Comment by jsevo** [comment]
The project needs not solve user input problems. Strict intstructions and a single error should suffice.

**Comment by granthussey** [comment]
Sure, I can make those changes! I also just need to strip out the logging, honestly. I never got it to work as I wanted.

**Comment by granthussey** [comment]
The first error happened because we don't accept numpy arrays. The second one happened because "index_column" needs to be the name of the index in the `microbiome_data`/`rel_abundances` dataframe (which it wasn't in your case). We can easily strip out the logging like I've said before and just use the warnings package to provide a few targeted error messages.

**Comment by granthussey** [comment]
Also, see #16 @jsevo
